# Generated by Django 4.0.4 on 2022-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=128)),
                ('is_login', models.PositiveSmallIntegerField()),
                ('is_deleted', models.PositiveSmallIntegerField()),
                ('login_dt', models.DateTimeField()),
                ('logout_dt', models.DateTimeField()),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
    ]
